# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [1192]:
import numpy as np
import pandas as pd

In [1193]:
df_train=pd.read_csv("/kaggle/input/house-prices-advanced-regression-techniques/train.csv")
df_test=pd.read_csv("/kaggle/input/house-prices-advanced-regression-techniques/test.csv")

In [1194]:
df_train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [1195]:
df_train.isnull().sum().sort_values(ascending=True)

Id                  0
TotalBsmtSF         0
Heating             0
SaleCondition       0
CentralAir          0
                 ...
MasVnrType        872
Fence            1179
Alley            1369
MiscFeature      1406
PoolQC           1453
Length: 81, dtype: int64

In [1196]:
df_train

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [1197]:
cols=['LotFrontage','FireplaceQu'       
,'MasVnrType'        
,'Fence'           
,'Alley'            
,'MiscFeature'      
,'PoolQC']

In [1198]:
df_train.drop(columns=cols,inplace=True)
df_test.drop(columns=cols,inplace=True)

In [1199]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 74 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotArea        1460 non-null   int64
 4   Street         1460 non-null   object
 5   LotShape       1460 non-null   object
 6   LandContour    1460 non-null   object
 7   Utilities      1460 non-null   object
 8   LotConfig      1460 non-null   object
 9   LandSlope      1460 non-null   object
 10  Neighborhood   1460 non-null   object
 11  Condition1     1460 non-null   object
 12  Condition2     1460 non-null   object
 13  BldgType       1460 non-null   object
 14  HouseStyle     1460 non-null   object
 15  OverallQual    1460 non-null   int64
 16  OverallCond    1460 non-null   int64
 17  YearBuilt      1460 non-null   int64
 18  YearRemodAdd   1460 non-null   int64
 19  RoofStyle      1460 non-null   object
 20  RoofMatl       1460 non-null   object
 21  Exterior1st    1460 non-null   object
 22  Exterior2nd    1460 non-null   object
 23  MasVnrArea     1452 non-null   float64
 24  ExterQual      1460 non-null   object
 25  ExterCond      1460 non-null   object
 26  Foundation     1460 non-null   object
 27  BsmtQual       1423 non-null   object
 28  BsmtCond       1423 non-null   object
 29  BsmtExposure   1422 non-null   object
 30  BsmtFinType1   1423 non-null   object
 31  BsmtFinSF1     1460 non-null   int64
 32  BsmtFinType2   1422 non-null   object
 33  BsmtFinSF2     1460 non-null   int64
 34  BsmtUnfSF      1460 non-null   int64
 35  TotalBsmtSF    1460 non-null   int64
 36  Heating        1460 non-null   object
 37  HeatingQC      1460 non-null   object
 38  CentralAir     1460 non-null   object
 39  Electrical     1459 non-null   object
 40  1stFlrSF       1460 non-null   int64
 41  2ndFlrSF       1460 non-null   int64
 42  LowQualFinSF   1460 non-null   int64
 43  GrLivArea      1460 non-null   int64
 44  BsmtFullBath   1460 non-null   int64
 45  BsmtHalfBath   1460 non-null   int64
 46  FullBath       1460 non-null   int64
 47  HalfBath       1460 non-null   int64
 48  BedroomAbvGr   1460 non-null   int64
 49  KitchenAbvGr   1460 non-null   int64
 50  KitchenQual    1460 non-null   object
 51  TotRmsAbvGrd   1460 non-null   int64
 52  Functional     1460 non-null   object
 53  Fireplaces     1460 non-null   int64
 54  GarageType     1379 non-null   object
 55  GarageYrBlt    1379 non-null   float64
 56  GarageFinish   1379 non-null   object
 57  GarageCars     1460 non-null   int64
 58  GarageArea     1460 non-null   int64
 59  GarageQual     1379 non-null   object
 60  GarageCond     1379 non-null   object
 61  PavedDrive     1460 non-null   object
 62  WoodDeckSF     1460 non-null   int64
 63  OpenPorchSF    1460 non-null   int64
 64  EnclosedPorch  1460 non-null   int64
 65  3SsnPorch      1460 non-null   int64
 66  ScreenPorch    1460 non-null   int64
 67  PoolArea       1460 non-null   int64
 68  MiscVal        1460 non-null   int64
 69  MoSold         1460 non-null   int64
 70  YrSold         1460 non-null   int64
 71  SaleType       1460 non-null   object
 72  SaleCondition  1460 non-null   object
 73  SalePrice      1460 non-null   int64
dtypes: float64(2), int64(35), object(37)
memory usage: 844.2+ KB

In [1200]:
object_columns = df_train.select_dtypes(include=['object'])
object_columns_test= df_test.select_dtypes(include=['object'])
# object_columns

In [1201]:
for column in object_columns.columns:
    unique_values = object_columns[column].unique()
    value_counts = object_columns[column].value_counts()
    
    print(f"Column: {column}")
    print(f"Unique Values: {unique_values}")
    print(f"Value Counts:\n{value_counts}\n")

Column: MSZoning
Unique Values: ['RL' 'RM' 'C (all)' 'FV' 'RH']
Value Counts:
MSZoning
RL         1151
RM          218
FV           65
RH           16
C (all)      10
Name: count, dtype: int64

Column: Street
Unique Values: ['Pave' 'Grvl']
Value Counts:
Street
Pave    1454
Grvl       6
Name: count, dtype: int64

Column: LotShape
Unique Values: ['Reg' 'IR1' 'IR2' 'IR3']
Value Counts:
LotShape
Reg    925
IR1    484
IR2     41
IR3     10
Name: count, dtype: int64

Column: LandContour
Unique Values: ['Lvl' 'Bnk' 'Low' 'HLS']
Value Counts:
LandContour
Lvl    1311
Bnk      63
HLS      50
Low      36
Name: count, dtype: int64

Column: Utilities
Unique Values: ['AllPub' 'NoSeWa']
Value Counts:
Utilities
AllPub    1459
NoSeWa       1
Name: count, dtype: int64

Column: LotConfig
Unique Values: ['Inside' 'FR2' 'Corner' 'CulDSac' 'FR3']
Value Counts:
LotConfig
Inside     1052
Corner      263
CulDSac      94
FR2          47
FR3           4
Name: count, dtype: int64

Column: LandSlope
Unique Values: ['Gtl' 'Mod' 'Sev']
Value Counts:
LandSlope
Gtl    1382
Mod      65
Sev      13
Name: count, dtype: int64

Column: Neighborhood
Unique Values: ['CollgCr' 'Veenker' 'Crawfor' 'NoRidge' 'Mitchel' 'Somerst' 'NWAmes'
 'OldTown' 'BrkSide' 'Sawyer' 'NridgHt' 'NAmes' 'SawyerW' 'IDOTRR'
 'MeadowV' 'Edwards' 'Timber' 'Gilbert' 'StoneBr' 'ClearCr' 'NPkVill'
 'Blmngtn' 'BrDale' 'SWISU' 'Blueste']
Value Counts:
Neighborhood
NAmes      225
CollgCr    150
OldTown    113
Edwards    100
Somerst     86
Gilbert     79
NridgHt     77
Sawyer      74
NWAmes      73
SawyerW     59
BrkSide     58
Crawfor     51
Mitchel     49
NoRidge     41
Timber      38
IDOTRR      37
ClearCr     28
StoneBr     25
SWISU       25
MeadowV     17
Blmngtn     17
BrDale      16
Veenker     11
NPkVill      9
Blueste      2
Name: count, dtype: int64

Column: Condition1
Unique Values: ['Norm' 'Feedr' 'PosN' 'Artery' 'RRAe' 'RRNn' 'RRAn' 'PosA' 'RRNe']
Value Counts:
Condition1
Norm      1260
Feedr       81
Artery      48
RRAn        26
PosN        19
RRAe        11
PosA         8
RRNn         5
RRNe         2
Name: count, dtype: int64

Column: Condition2
Unique Values: ['Norm' 'Artery' 'RRNn' 'Feedr' 'PosN' 'PosA' 'RRAn' 'RRAe']
Value Counts:
Condition2
Norm      1445
Feedr        6
Artery       2
RRNn         2
PosN         2
PosA         1
RRAn         1
RRAe         1
Name: count, dtype: int64

Column: BldgType
Unique Values: ['1Fam' '2fmCon' 'Duplex' 'TwnhsE' 'Twnhs']
Value Counts:
BldgType
1Fam      1220
TwnhsE     114
Duplex      52
Twnhs       43
2fmCon      31
Name: count, dtype: int64

Column: HouseStyle
Unique Values: ['2Story' '1Story' '1.5Fin' '1.5Unf' 'SFoyer' 'SLvl' '2.5Unf' '2.5Fin']
Value Counts:
HouseStyle
1Story    726
2Story    445
1.5Fin    154
SLvl       65
SFoyer     37
1.5Unf     14
2.5Unf     11
2.5Fin      8
Name: count, dtype: int64

Column: RoofStyle
Unique Values: ['Gable' 'Hip' 'Gambrel' 'Mansard' 'Flat' 'Shed']
Value Counts:
RoofStyle
Gable      1141
Hip         286
Flat         13
Gambrel      11
Mansard       7
Shed          2
Name: count, dtype: int64

Column: RoofMatl
Unique Values: ['CompShg' 'WdShngl' 'Metal' 'WdShake' 'Membran' 'Tar&Grv' 'Roll'
 'ClyTile']
Value Counts:
RoofMatl
CompShg    1434
Tar&Grv      11
WdShngl       6
WdShake       5
Metal         1
Membran       1
Roll          1
ClyTile       1
Name: count, dtype: int64

Column: Exterior1st
Unique Values: ['VinylSd' 'MetalSd' 'Wd Sdng' 'HdBoard' 'BrkFace' 'WdShing' 'CemntBd'
 'Plywood' 'AsbShng' 'Stucco' 'BrkComm' 'AsphShn' 'Stone' 'ImStucc'
 'CBlock']
Value Counts:
Exterior1st
VinylSd    515
HdBoard    222
MetalSd    220
Wd Sdng    206
Plywood    108
CemntBd     61
BrkFace     50
WdShing     26
Stucco      25
AsbShng     20
BrkComm      2
Stone        2
AsphShn      1
ImStucc      1
CBlock       1
Name: count, dtype: int64

Column: Exterior2nd
Unique Values: ['VinylSd' 'MetalSd' 'Wd Shng' 'HdBoard' 'Plywood' 'Wd Sdng' 'CmentBd'
 'BrkFace' 'Stucco' 'AsbShng' 'Brk Cmn' 'ImStucc' 'AsphShn' 'Stone'
 'Other' 'CBlock']
Value Counts:
Exterior2nd
VinylSd    504
MetalSd    214
HdBoard    207
Wd Sdng    197
Plywood    142
CmentBd     60
Wd Shng     38
Stucco      26
BrkFace     25
AsbShng     20
ImStucc     10
Brk Cmn      7
Stone        5
AsphShn      3
Other        1
CBlock       1
Name: count, dtype: int64

Column: ExterQual
Unique Values: ['Gd' 'TA' 'Ex' 'Fa']
Value Counts:
ExterQual
TA    906
Gd    488
Ex     52
Fa     14
Name: count, dtype: int64

Column: ExterCond
Unique Values: ['TA' 'Gd' 'Fa' 'Po' 'Ex']
Value Counts:
ExterCond
TA    1282
Gd     146
Fa      28
Ex       3
Po       1
Name: count, dtype: int64

Column: Foundation
Unique Values: ['PConc' 'CBlock' 'BrkTil' 'Wood' 'Slab' 'Stone']
Value Counts:
Foundation
PConc     647
CBlock    634
BrkTil    146
Slab       24
Stone       6
Wood        3
Name: count, dtype: int64

Column: BsmtQual
Unique Values: ['Gd' 'TA' 'Ex' nan 'Fa']
Value Counts:
BsmtQual
TA    649
Gd    618
Ex    121
Fa     35
Name: count, dtype: int64

Column: BsmtCond
Unique Values: ['TA' 'Gd' nan 'Fa' 'Po']
Value Counts:
BsmtCond
TA    1311
Gd      65
Fa      45
Po       2
Name: count, dtype: int64

Column: BsmtExposure
Unique Values: ['No' 'Gd' 'Mn' 'Av' nan]
Value Counts:
BsmtExposure
No    953
Av    221
Gd    134
Mn    114
Name: count, dtype: int64

Column: BsmtFinType1
Unique Values: ['GLQ' 'ALQ' 'Unf' 'Rec' 'BLQ' nan 'LwQ']
Value Counts:
BsmtFinType1
Unf    430
GLQ    418
ALQ    220
BLQ    148
Rec    133
LwQ     74
Name: count, dtype: int64

Column: BsmtFinType2
Unique Values: ['Unf' 'BLQ' nan 'ALQ' 'Rec' 'LwQ' 'GLQ']
Value Counts:
BsmtFinType2
Unf    1256
Rec      54
LwQ      46
BLQ      33
ALQ      19
GLQ      14
Name: count, dtype: int64

Column: Heating
Unique Values: ['GasA' 'GasW' 'Grav' 'Wall' 'OthW' 'Floor']
Value Counts:
Heating
GasA     1428
GasW       18
Grav        7
Wall        4
OthW        2
Floor       1
Name: count, dtype: int64

Column: HeatingQC
Unique Values: ['Ex' 'Gd' 'TA' 'Fa' 'Po']
Value Counts:
HeatingQC
Ex    741
TA    428
Gd    241
Fa     49
Po      1
Name: count, dtype: int64

Column: CentralAir
Unique Values: ['Y' 'N']
Value Counts:
CentralAir
Y    1365
N      95
Name: count, dtype: int64

Column: Electrical
Unique Values: ['SBrkr' 'FuseF' 'FuseA' 'FuseP' 'Mix' nan]
Value Counts:
Electrical
SBrkr    1334
FuseA      94
FuseF      27
FuseP       3
Mix         1
Name: count, dtype: int64

Column: KitchenQual
Unique Values: ['Gd' 'TA' 'Ex' 'Fa']
Value Counts:
KitchenQual
TA    735
Gd    586
Ex    100
Fa     39
Name: count, dtype: int64

Column: Functional
Unique Values: ['Typ' 'Min1' 'Maj1' 'Min2' 'Mod' 'Maj2' 'Sev']
Value Counts:
Functional
Typ     1360
Min2      34
Min1      31
Mod       15
Maj1      14
Maj2       5
Sev        1
Name: count, dtype: int64

Column: GarageType
Unique Values: ['Attchd' 'Detchd' 'BuiltIn' 'CarPort' nan 'Basment' '2Types']
Value Counts:
GarageType
Attchd     870
Detchd     387
BuiltIn     88
Basment     19
CarPort      9
2Types       6
Name: count, dtype: int64

Column: GarageFinish
Unique Values: ['RFn' 'Unf' 'Fin' nan]
Value Counts:
GarageFinish
Unf    605
RFn    422
Fin    352
Name: count, dtype: int64

Column: GarageQual
Unique Values: ['TA' 'Fa' 'Gd' nan 'Ex' 'Po']
Value Counts:
GarageQual
TA    1311
Fa      48
Gd      14
Ex       3
Po       3
Name: count, dtype: int64

Column: GarageCond
Unique Values: ['TA' 'Fa' nan 'Gd' 'Po' 'Ex']
Value Counts:
GarageCond
TA    1326
Fa      35
Gd       9
Po       7
Ex       2
Name: count, dtype: int64

Column: PavedDrive
Unique Values: ['Y' 'N' 'P']
Value Counts:
PavedDrive
Y    1340
N      90
P      30
Name: count, dtype: int64

Column: SaleType
Unique Values: ['WD' 'New' 'COD' 'ConLD' 'ConLI' 'CWD' 'ConLw' 'Con' 'Oth']
Value Counts:
SaleType
WD       1267
New       122
COD        43
ConLD       9
ConLI       5
ConLw       5
CWD         4
Oth         3
Con         2
Name: count, dtype: int64

Column: SaleCondition
Unique Values: ['Normal' 'Abnorml' 'Partial' 'AdjLand' 'Alloca' 'Family']
Value Counts:
SaleCondition
Normal     1198
Partial     125
Abnorml     101
Family       20
Alloca       12
AdjLand       4
Name: count, dtype: int64

In [1202]:
# Removed this step since simplely dropping rest of the null datapoint .... reduces rmse value furthur from 31k to 28k
# df_train_modified = df_train.fillna(df_train.mode().iloc[0])
# df_test_modified = df_test.fillna(df_test.mode().iloc[0])

In [1203]:
# df_train_modified.info()

In [1204]:
df_train.shape

(1460, 74)

In [1205]:
df_test.shape

(1459, 73)

In [1206]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 73 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1459 non-null   int64
 1   MSSubClass     1459 non-null   int64
 2   MSZoning       1455 non-null   object
 3   LotArea        1459 non-null   int64
 4   Street         1459 non-null   object
 5   LotShape       1459 non-null   object
 6   LandContour    1459 non-null   object
 7   Utilities      1457 non-null   object
 8   LotConfig      1459 non-null   object
 9   LandSlope      1459 non-null   object
 10  Neighborhood   1459 non-null   object
 11  Condition1     1459 non-null   object
 12  Condition2     1459 non-null   object
 13  BldgType       1459 non-null   object
 14  HouseStyle     1459 non-null   object
 15  OverallQual    1459 non-null   int64
 16  OverallCond    1459 non-null   int64
 17  YearBuilt      1459 non-null   int64
 18  YearRemodAdd   1459 non-null   int64
 19  RoofStyle      1459 non-null   object
 20  RoofMatl       1459 non-null   object
 21  Exterior1st    1458 non-null   object
 22  Exterior2nd    1458 non-null   object
 23  MasVnrArea     1444 non-null   float64
 24  ExterQual      1459 non-null   object
 25  ExterCond      1459 non-null   object
 26  Foundation     1459 non-null   object
 27  BsmtQual       1415 non-null   object
 28  BsmtCond       1414 non-null   object
 29  BsmtExposure   1415 non-null   object
 30  BsmtFinType1   1417 non-null   object
 31  BsmtFinSF1     1458 non-null   float64
 32  BsmtFinType2   1417 non-null   object
 33  BsmtFinSF2     1458 non-null   float64
 34  BsmtUnfSF      1458 non-null   float64
 35  TotalBsmtSF    1458 non-null   float64
 36  Heating        1459 non-null   object
 37  HeatingQC      1459 non-null   object
 38  CentralAir     1459 non-null   object
 39  Electrical     1459 non-null   object
 40  1stFlrSF       1459 non-null   int64
 41  2ndFlrSF       1459 non-null   int64
 42  LowQualFinSF   1459 non-null   int64
 43  GrLivArea      1459 non-null   int64
 44  BsmtFullBath   1457 non-null   float64
 45  BsmtHalfBath   1457 non-null   float64
 46  FullBath       1459 non-null   int64
 47  HalfBath       1459 non-null   int64
 48  BedroomAbvGr   1459 non-null   int64
 49  KitchenAbvGr   1459 non-null   int64
 50  KitchenQual    1458 non-null   object
 51  TotRmsAbvGrd   1459 non-null   int64
 52  Functional     1457 non-null   object
 53  Fireplaces     1459 non-null   int64
 54  GarageType     1383 non-null   object
 55  GarageYrBlt    1381 non-null   float64
 56  GarageFinish   1381 non-null   object
 57  GarageCars     1458 non-null   float64
 58  GarageArea     1458 non-null   float64
 59  GarageQual     1381 non-null   object
 60  GarageCond     1381 non-null   object
 61  PavedDrive     1459 non-null   object
 62  WoodDeckSF     1459 non-null   int64
 63  OpenPorchSF    1459 non-null   int64
 64  EnclosedPorch  1459 non-null   int64
 65  3SsnPorch      1459 non-null   int64
 66  ScreenPorch    1459 non-null   int64
 67  PoolArea       1459 non-null   int64
 68  MiscVal        1459 non-null   int64
 69  MoSold         1459 non-null   int64
 70  YrSold         1459 non-null   int64
 71  SaleType       1458 non-null   object
 72  SaleCondition  1459 non-null   object
dtypes: float64(10), int64(26), object(37)
memory usage: 832.2+ KB

In [1207]:
df_train.dropna(inplace=True)

In [1208]:
# gotta drop separate label from train
df_train_labels=df_train['SalePrice']
df_train=df_train.drop(columns=['SalePrice'],axis=1)

In [1209]:
df_train.shape

(1338, 73)

In [1210]:
df_test.shape

(1459, 73)

In [1211]:
# train_columns = set(df_train.columns)
# test_columns = set(df_test.columns)

# # Check if the column sets are the same
# if train_columns == test_columns:
#     print("Training and test datasets have the same features.")
# else:
#     print("Training and test datasets have different features.")

In [1212]:
# Select only the columns with data type 'object'
object_columns = df_train.select_dtypes(include=['object'])
object_columns_test = df_test.select_dtypes(include=['object'])

# Perform one-hot encoding on the object columns
object_columns_encoded = pd.get_dummies(object_columns, drop_first=True)
object_columns_test_encoded = pd.get_dummies(object_columns_test, drop_first=True)

# Concatenate the one-hot encoded object columns with the original DataFrame
df_train_encoded = pd.concat([df_train.drop(object_columns.columns, axis=1), object_columns_encoded], axis=1)
df_test_encoded = pd.concat([df_test.drop(object_columns_test.columns, axis=1), object_columns_test_encoded], axis=1)

In [1213]:
df_train_encoded.shape

(1338, 224)

In [1214]:
df_test_encoded.shape

(1459, 213)

> different numbers of columns i,e features after encoding means maybe different features in dfs

In [1215]:
train_columns = set(df_train_encoded.columns)
test_columns = set(df_test_encoded.columns)

# Check if the column sets are the same
if train_columns == test_columns:
    print("encoded Training and test datasets have the same features.")
else:
    print("encoded Training and test datasets have different features.")

encoded Training and test datasets have different features.

In [1216]:
# Get the column names of the training and test datasets
train_columns = set(df_train_encoded.columns)
test_columns = set(df_test_encoded.columns)

# Find columns unique to each dataset
train_unique_columns = train_columns - test_columns
test_unique_columns = test_columns - train_columns

# Print the differences
print("Columns unique to the training dataset:")
for column in train_unique_columns:
    print(column)

print("\nColumns unique to the test dataset:")
for column in test_unique_columns:
    print(column)

Columns unique to the training dataset:
RoofMatl_CompShg
Exterior1st_Stone
Exterior1st_ImStucc
Condition2_RRAe
RoofMatl_Metal
Heating_OthW
Exterior2nd_Other
Condition2_RRNn
RoofMatl_Membran
Electrical_Mix
GarageQual_Fa
RoofMatl_Roll
HouseStyle_2.5Fin
Condition2_RRAn
Utilities_NoSeWa

Columns unique to the test dataset:
Heating_Wall
Foundation_Slab
ExterCond_Po
Exterior1st_AsphShn

In [1217]:
import pandas as pd

# Assuming you have x_train and x_test DataFrames
# Replace these with your actual data
# x_train = ...
# x_test = ...

# Columns unique to the training dataset
train_unique_columns = [
    'RoofMatl_CompShg',
    'Exterior1st_Stone',
    'Exterior1st_ImStucc',
    'Condition2_RRAe',
    'RoofMatl_Metal',
    'Heating_OthW',
    'Exterior2nd_Other',
    'Condition2_RRNn',
    'RoofMatl_Membran',
    'Electrical_Mix',
    'GarageQual_Fa',
    'RoofMatl_Roll',
    'HouseStyle_2.5Fin',
    'Condition2_RRAn',
    'Utilities_NoSeWa'
]

# Columns unique to the test dataset
test_unique_columns = [
    'Heating_Wall',
    'Foundation_Slab',
    'ExterCond_Po',
    'Exterior1st_AsphShn'  # Add other test unique columns here
]

# Drop the unique columns from their respective DataFrames
df_train_encoded.drop(columns=train_unique_columns, inplace=True)
df_test_encoded.drop(columns=test_unique_columns, inplace=True)

# Now, df_train_encoded and df_test_encoded no longer contain the unique columns

In [1218]:
df_train_encoded.isnull().sum().sum()

0

In [1219]:
df_train_encoded.shape

(1338, 209)

In [1220]:
df_test_encoded.shape

(1459, 209)

In [1221]:
# gotta drop saleprice label before encoding otherwise there would be mismatch in feature numbers in x_train and x_test 
# # moved this cell down by two unit
# x=df_train_encoded.drop(columns=['SalePrice'],axis=1)
# y=df_train_encoded['SalePrice']

In [1222]:
x=df_train_encoded
y=df_train_labels

In [1223]:
x.shape

(1338, 209)

In [1224]:
from sklearn.model_selection import train_test_split
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=0.2, random_state=42)

In [1225]:
from sklearn.decomposition import PCA

In [1226]:
x_train.isnull().sum().sum()

0

In [1227]:
x_val.isnull().sum().sum()

0

In [1228]:
x_test=df_test_modified

In [1229]:
# Apply PCA to reduce the dimensionality of the feature space
#n_components =75  # You can choose the number of components based on your preference or analysis
#pca = PCA(n_components=n_components)
#x_train_pca = pca.fit_transform(x_train)
#x_val_pca = pca.fit_transform(x_val)

In [1230]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error
model = xgb.XGBRegressor(objective='reg:squarederror')
model.fit(x_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [1231]:
y_pred = model.predict(x_val)

In [1232]:
mse = mean_squared_error(y_val, y_pred)
rmse = np.sqrt(mse)
print(f"Root Mean Squared Error: {rmse:.2f}")

Root Mean Squared Error: 26774.22

In [1233]:
y_pred_test=model.predict(df_test_encoded)

In [1234]:
y_pred_test

array([129852.82 , 166856.22 , 184655.02 , ..., 170753.27 , 121420.625,
       212053.16 ], dtype=float32)

In [1235]:
submission = df_test[["Id"]]

In [1236]:
submission["SalePrice"] = y_pred_test

/tmp/ipykernel_32/4181421123.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  submission["SalePrice"] = y_pred_test

In [1237]:
submission

        Id      SalePrice
0     1461  129852.820312
1     1462  166856.218750
2     1463  184655.015625
3     1464  200615.593750
4     1465  210120.046875
...    ...            ...
1454  2915   72832.546875
1455  2916   78323.078125
1456  2917  170753.265625
1457  2918  121420.625000
1458  2919  212053.156250

[1459 rows x 2 columns]

In [1238]:
submission.to_csv("submission.csv",index=None)

In [1239]:
pd.read_csv("submission.csv")

        Id   SalePrice
0     1461  129852.820
1     1462  166856.220
2     1463  184655.020
3     1464  200615.600
4     1465  210120.050
...    ...         ...
1454  2915   72832.550
1455  2916   78323.080
1456  2917  170753.270
1457  2918  121420.625
1458  2919  212053.160

[1459 rows x 2 columns]